apiVersion: v1
kind: Namespace
metadata:
  name: chat-app
  labels:
    name: chat-app
    helm.sh/chart: chat-app-1.0.0
    app.kubernetes.io/name: chat-app
    app.kubernetes.io/managed-by: Helm
