apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    helm.sh/chart: chat-app-1.0.0
    app.kubernetes.io/name: chat-app
    app.kubernetes.io/managed-by: Helm
