apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
  namespace: chat-app
  labels:
    helm.sh/chart: chat-app-1.0.0
    app.kubernetes.io/name: chat-app
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  DB_PASS: "Y2hhdHBhc3M="
  POSTGRES_PASSWORD: "Y2hhdHBhc3M="
  REDIS_PASSWORD: ""
